language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
  - make build
script:
  - hack/test-headless.sh test
  - hack/verify-dist.sh
