language: node_js
node_js:
  - "4"
cache:
  directories:
  - node_modules
  - bower_components
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_script:
  - make build
script:
  - hack/test-headless.sh test
  - hack/verify-dist.sh
