'use strict';

angular.module('openshiftCommonServices')
  .constant('API_PREFERRED_VERSIONS', {
    appliedclusterresourcequotas:     {group: 'quota.openshift.io',     resource: 'appliedclusterresourcequotas' },
    builds:                           {group: 'build.openshift.io',     resource: 'builds' },
    'builds/clone':                   {group: 'build.openshift.io',     resource: 'builds/clone' },
    'buildconfigs/instantiate':       {group: 'build.openshift.io',     resource: 'buildconfigs/instantiate' },
    buildconfigs:                     {group: 'build.openshift.io',     resource: 'buildconfigs' },
    configmaps:                       'configmaps',
    deployments:                      {group: 'apps',                   resource: 'deployments' },
    deploymentconfigs:                {group: 'apps.openshift.io',      resource: 'deploymentconfigs' },
    'deploymentconfigs/instantiate':  {group: 'apps.openshift.io',      resource: 'deploymentconfigs/instantiate' },
    'deploymentconfigs/rollback':     {group: 'apps.openshift.io',      resource: 'deploymentconfigs/rollback' },
    events:                           'events',
    horizontalpodautoscalers:         {group: 'autoscaling',            resource: 'horizontalpodautoscalers' },
    imagestreams:                     {group: 'image.openshift.io',     resource: 'imagestreams' },
    imagestreamtags:                  {group: 'image.openshift.io',     resource: 'imagestreamtags' },
    limitranges:                      'limitranges',
    pods:                             'pods',
    projects:                         {group: 'project.openshift.io',   resource: 'projects'},
    projectrequests:                  {group: 'project.openshift.io',   resource: 'projectrequests'},
    persistentvolumeclaims:           'persistentvolumeclaims',
    replicasets:                      {group: 'extensions',             resource: 'replicasets' },
    replicationcontrollers:           'replicationcontrollers',
    resourcequotas:                   'resourcequotas',
    rolebindings:                     'rolebindings',
    routes:                           {group: 'route.openshift.io',     resource: 'routes' },
    secrets:                          'secrets',
    selfsubjectrulesreviews:          {group: 'authorization.k8s.io',   resource: 'selfsubjectrulesreviews'},
    services:                         'services',
    serviceaccounts:                  'serviceaccounts',
    serviceclasses:                   {group: 'servicecatalog.k8s.io',  resource: 'serviceclasses' },
    serviceinstancecredentials:       {group: 'servicecatalog.k8s.io',  resource: 'serviceinstancecredentials' },
    serviceinstances:                 {group: 'servicecatalog.k8s.io',  resource: 'serviceinstances' },
    statefulsets:                     {group: 'apps',                   resource: 'statefulsets' },
    templates:                        {group: 'template.openshift.io',  resource: 'templates'}
  });
